# Generated by Django 3.1.7 on 2021-05-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('category', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('images', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
