# Generated by Django 3.1.7 on 2021-05-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
